title: Chaithanya Kumar A
author:
  name: Chaithanya Kumar A
  email: chaithanya.kumar42a@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  I like physics , training & building small to large scale AI models , taking long
  aimless walks In the nature and reading PG essays. I love writing & sharing my thoughts on 
  everything that has helped me become a better human. checkout the blogs section. Happy reading :)

# Build settings
# Using custom theme instead of minima
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Add this under plugins section
collections:
  curiosity:
    output: true

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - blog.md
  - curiosity.md
  - list-100.md
  - quotes.md
  - about.md

# Custom theme settings
show_excerpts: false

# Social links
social_links:
  - { platform: x,              user_url: "https://x.com/ChaithanyaK42" }
  - { platform: github,         user_url: "https://github.com/chaithanyak42" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/chaithanya-kumar-a-610a91167/" }

disqus:
  shortname: cosmos42
